### ISSUE TITLE
"Harmlessness" does nothing when played if cleansed and played on turn 1

### ISSUE THREAD

**Issue by jjpdx** [gygrazok/witchmod#6] opened 2018-04-21 08:51 UTC

**Comment by jjpdx** [comment] 2018-04-21 08:55
Update: Only happens if you had it in your starting hand.

**Comment by jjpdx** [comment] 2018-04-22 18:55
Update: Actually happens if you cleanse it the turn it is "created." If you get one from Dead Branch and cleanse it the same turn, it also does nothing when played.

**Comment by gygrazok** [comment] 2018-04-23 21:33
Should be fixed in the current (0.7) release. Thanks for the report

**Comment by SirHaesslich** [comment] 2018-05-18 11:00
It did not get fixed. Yesterday I tried to play it the turn it was cleansed and it did nothing. But now it does correctly calculate damage if it actually deals it at all

**Comment by Astralika** [comment] 2018-06-12 03:50
Happened again, though I can confirm this time it was because I'd drawn it with Wicked Thoughts.

**Comment by gygrazok** [comment] 2018-06-24 10:56
Fixed. Thanks.

**Closed by gygrazok** 2018-06-24 10:56 UTC
