### ISSUE TITLE
Wretched Nails card crashes when drawn by the Ironclad

### ISSUE THREAD

**Issue by Ordinaryperson2** [gygrazok/witchmod#21] opened 2018-07-28 14:31 UTC
I had the probably inadvisable idea of turning on a few character mods, then playing a game with the modifier that gives you cards from all classes.
Wretched Nails was added to my deck by the Replay the Spire elite that thickens your deck. Later in the fight when I drew cards at the start of the turn, the game closed. This is in the error log:
```
java.lang.ClassCastException: com.megacrit.cardcrawl.characters.Ironclad cannot be cast to witchmod.characters.WitchCharacter
	at witchmod.cards.WretchedNails.calculateModifiedCardDamage(WretchedNails.java:80) ~[WitchMod.jar:?]
	at witchmod.cards.WretchedNails.applyPowers(WretchedNails.java:56) ~[WitchMod.jar:?]
	at com.megacrit.cardcrawl.cards.CardGroup.applyPowers(CardGroup.java:183) ~[?:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.onCardDrawOrDiscard(AbstractPlayer.java:1459) ~[?:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.draw(AbstractPlayer.java:1825) ~[?:?]
	at com.megacrit.cardcrawl.actions.common.DrawCardAction.update(DrawCardAction.java:100) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:152) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:257) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2635) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:825) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
```
Plenty of other witch cards worked fine for me (Mercury Wand, Bewitch, Mortus Claw, etc) so the issue is probably specific to this card.

**Comment by gygrazok** [comment] 2018-07-29 17:32
Hi, the error is caused by the fact that the ironclad (and any other character) doesn't track the number of cards drawn in a turn turn (it's a variable only used by the witch). When the card tries to recover that number, it fails if the character is not the witch. 
I'll try to fix it in the next release.

Thanks for the report!

**Comment by gygrazok** [comment] 2018-09-01 01:01
Should be fixed in the latest release.

**Closed by gygrazok** 2018-09-01 01:01 UTC
